### ISSUE TITLE
Relax  CMake ≥ 3.20 requirement

### ISSUE THREAD

**Issue by tbeu** [cleancode-cpp/cmake-testsetup#2]
I noticed that CMake &GreaterEqual; 3.20 is required. By relaxing that requirement I checked with CMake 3.12 (of VS 2017) and could run it succesfully. Is there any feature of CMake > 3.12 utilized such that it is required to stick with newer versions?

**Comment by arBmind** [comment]
@tbeu This repository is mainly used to test the customer build setups for the practical sessions of my Clean Code C++ training courses. For each training the setup varies slightly.
VS2017 is usually not used, but there is a special branch for that, in case it's needed.
CMake <3.20 lacks the support for CMakePresets.json and therefore is a bit harder to set up.

**Comment by tbeu** [comment]
Alright, thanks for clarification.
